# Generated by Django 5.2.6 on 2025-09-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge',
            field=models.CharField(choices=[('none', 'None'), ('bronze', '🥉 Bronze'), ('silver', '🥈 Silver'), ('gold', '🥇 Gold'), ('diamond', '💎 Diamond')], default='none', max_length=20),
        ),
    ]
