# Generated by Django 5.2.6 on 2025-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_badge_user_admission_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_of_admission',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
