# Generated by Django 5.2.6 on 2025-10-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_admission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_of_admission',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('welfare', 'Welfare'), ('storekeeper', 'Storekeeper'), ('admin', 'Admin')], default='welfare', max_length=20),
        ),
        migrations.DeleteModel(
            name='BroughtBy',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
