# Generated by Django 5.2.6 on 2025-10-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_medicalrecord_student_and_more'),
    ]

    operations = [
    ]
