# Generated by Django 5.2.6 on 2025-10-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_update_beneficiary_model'),
    ]

    operations = [
    ]
