# Generated by Django 5.2.6 on 2025-09-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_custom_name_alter_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='out_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
